### PR TITLE
Makefile Compiling

### PR DESCRIPTION
**Pull request by NullVoxPopuli**
Not ready for merge. Just wanted to track changes and have an ongoing indicator of merge compatibility.

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
I've also added to the readme for how to install the ffmpeg dependencies.

Current issue: 

    Source/Core/EntryPoint.cpp: In function ‘int main(int, char**)’:
    Source/Core/EntryPoint.cpp:12:49: error: ‘_fullpath’ was not declared in this scope
      _fullpath(base_path, argv[0], sizeof(base_path));
                                                 ^

**Comment by etkirsch** [comment]
Is this PR ready for merge?

**Comment by etkirsch** [comment]
also does it break VC++ support?

**Comment by NullVoxPopuli** [comment]
Not sure if it breaks VC++ support. You might need to re-configure the project. I know where is a 'makefile project' option.

**Comment by etkirsch** [comment]
I'll clone yours real quick and check

**Pull request merged**
